package com.toolshare.toolshare.model;

import lombok.*;

import javax.persistence.*;
import java.time.LocalDateTime;

@ToString
@Getter
@Setter
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor@Entity
@Table(name = "loan_actions")
public class LoanAction {

    //Defining id, ensuring it is generated by Spring and immutable
    @Id
    @SequenceGenerator(
            name = "loan_sequence",
            sequenceName = "loan_sequence",
            allocationSize = 1
    )
    @GeneratedValue(
            generator = "loan_sequence",
            strategy = GenerationType.SEQUENCE)
    private Long loanId;


    //Defining foreign-key relationship to itemId (mapping done in ShareItem class)
//    @Column(name = "item_id", nullable = false)
//    private Long itemId;

    //Defining time variable
    @Column(name = "loanTime", nullable = false)
    private LocalDateTime loanTime;

}
